// frontend-react/src/components/home/Home.tsx
import React, {useEffect, useState} from 'react';
import { FaHome, FaFolder, FaFileAlt, FaUser } from 'react-icons/fa'
import Landing from '../template/Landing';

import PageTitle from '../template/PageTitle';
import Stat from './Stat';
import api from '../../services/api';

import './styles/home.css'

interface Stats {
    users: number
    articles: number
    categories: number
}

function Home() {

    const [stats, setStats] = useState<Stats>()

    function getStats() {
        api.get('/stats')
            .then(res => {
                setStats({
                    users: res.data.users,
                    articles: res.data.articles,
                    categories: res.data.categories
                })
            })
    }

    useEffect(() => {
        getStats()
    }, [stats])

    return(
        <Landing>
            <div className="home">
                <PageTitle title="Dashboard" subtitle="Base de Conhecimento">
                    <FaHome />
                </PageTitle>
                <div className="stats">
                    <Stat title="Categorias" value={ stats ? stats.categories : 0 } color="#d54d50">
                        <FaFolder />
                    </Stat>
                    <Stat title="Artigos" value={ stats ? stats.articles : 0 } color="#3bc480">
                        <FaFileAlt />
                    </Stat>
                    <Stat title="Usuários" value={ stats ? stats.users : 0 } color="#3282cd">
                        <FaUser />
                    </Stat>
                </div>            
            </div>
        </Landing>
    )
}

export default Home;

// frontend/src/components/home/Home.vue
<template>
  <div class="home">
      <PageTitle icon="fa fa-home" main="Dashboard" sub="Base de Conhecimento" />
      <div class="stats">
        <Stat title="Categorias" :value="stat.categories" icon="fa fa-folder" color="#d54d50" />
        <Stat title="Artigos" :value="stat.articles" icon="fa fa-file" color="#3bc480" />
        <Stat title="Usuários" :value="stat.users" icon="fa fa-user" color="#3282cd" />
      </div>
  </div>
</template>

<script>
import PageTitle from '../template/PageTitle'
import Stat from './Stat'
import axios from 'axios'
import { baseApiUrl } from '@/global'

export default {
    name: "Home",
    components: { PageTitle, Stat },
    data: function() {
      return {
        stat: {}
      }
    },
    methods: {
      getStats() {
        axios.get(`${baseApiUrl}/stats`).then(res => this.stat = res.data)
      }
    },
    mounted() {
      this.getStats()
    }
}
</script>

<style>
  .stats {
    display: flex;
    justify-content: space-between;
    flex-wrap: wrap;
  }
</style>
