// frontend-react/src/components/admin/AdminPages.tsx
import React from 'react';
import { Tab, Tabs } from 'react-bootstrap';
import { FaCogs } from 'react-icons/fa';
import Landing from '../template/Landing';

import PageTitle from '../template/PageTitle';
import UserAdmin from './UserAdmin';
import CategoryAdmin from './CategoryAdmin'
import ArticleAdmin from './ArticleAdmin';

import './styles/adminPages.css'


function AdminPages() {


    return (
        <Landing>
            <div className="admin-pages">
                <PageTitle title="Administração do Sistema" subtitle="Cadastro & Cia">
                    <FaCogs />
                </PageTitle>
                <div className="admin-pages-tab">
                    <Tabs defaultActiveKey="articles">
                        <Tab eventKey="articles" title="Artigos">
                            <ArticleAdmin />
                        </Tab>
                        <Tab eventKey="categories" title="Categorias">
                            <CategoryAdmin />
                        </Tab>
                        <Tab eventKey="users" title="Usuários">
                            <UserAdmin />
                        </Tab>
                    </Tabs>
                </div>
            </div>
        </Landing>
    );
};

export default AdminPages;

// frontend/src/components/admin/AdminPages.vue
<template>
  <div class="admin-pages">
      <PageTitle icon="fa fa-cogs" main="Administração do Sistema" sub="Cadastro & Cia" />
      <div class="admin-pages-tabs">
          <b-card no-body>
            <b-tabs card>
              <b-tab title="Artigos" active>
                <ArticleAdmin />
              </b-tab>
              <b-tab title="Categorias">
                <CategoryAdmin />
              </b-tab>
              <b-tab title="Usuários">
                <UserAdmin />
              </b-tab>
            </b-tabs>
          </b-card>
      </div>
  </div>
</template>

<script>
import PageTitle from '../template/PageTitle'
import ArticleAdmin from './ArticleAdmin'
import CategoryAdmin from './CategoryAdmin'
import UserAdmin from './UserAdmin'

export default {
    name: "AdminPages",
    components: { PageTitle, ArticleAdmin, CategoryAdmin, UserAdmin }
}
</script>

<style>

</style>
